ARG BASE_IMAGE=nvidia/cuda:12.6.0-runtime-ubuntu22.04
FROM ${BASE_IMAGE}

ARG PYTHON_VERSION=3.12
ARG TORCH_CHANNEL=cu126
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common git curl && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-venv && \
    python${PYTHON_VERSION} -m ensurepip --upgrade && \
    rm -rf /var/lib/apt/lists/*

RUN python${PYTHON_VERSION} -m pip install --upgrade pip && \
    python${PYTHON_VERSION} -m pip install torch --extra-index-url https://download.pytorch.org/whl/${TORCH_CHANNEL}

COPY dist_for_image/*.whl /tmp/wheels/
RUN python${PYTHON_VERSION} -m pip install /tmp/wheels/*.whl && rm -rf /tmp/wheels

RUN update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1

WORKDIR /workspace
CMD ["python"]